# Files for testing google3.vr.perception.deepholodeck.human_correspondence.data.utils
filegroup(
    name = "test_mesh_file",
    srcs = [
        "renderpeople.obj",
        "test_mesh.pickle",
        "texture_map.jpg",
    ],
    visibility = [
        "//vr/perception/deepholodeck/human_correspondence/data:__subpackages__",
    ],
)
